-- Таблица комнат
CREATE TABLE IF NOT EXISTS game_rooms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id TEXT NOT NULL UNIQUE,
  room_name TEXT NOT NULL,
  game_type TEXT NOT NULL,
  created_by TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Таблица игроков в комнатах
CREATE TABLE IF NOT EXISTS game_players (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id TEXT NOT NULL,
  user_key TEXT NOT NULL,
  symbol TEXT NOT NULL CHECK (symbol IN ('X', 'O')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Индексы
CREATE INDEX IF NOT EXISTS idx_game_rooms_room_id ON game_rooms(room_id);
CREATE INDEX IF NOT EXISTS idx_game_rooms_game_type ON game_rooms(game_type);
CREATE INDEX IF NOT EXISTS idx_game_players_room_id ON game_players(room_id);
CREATE INDEX IF NOT EXISTS idx_game_players_user_key ON game_players(user_key);

-- Права
GRANT ALL ON game_rooms TO anon, authenticated;
GRANT ALL ON game_players TO anon, authenticated;
GRANT ALL ON SEQUENCE game_rooms_id_seq TO anon, authenticated;
GRANT ALL ON SEQUENCE game_players_id_seq TO anon, authenticated;

-- Функция для получения активных комнат
CREATE OR REPLACE FUNCTION get_active_rooms(p_game_type TEXT)
RETURNS TABLE(
  room_id TEXT,
  room_name TEXT,
  player_count BIGINT,
  created_at TIMESTAMP WITH TIME ZONE
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    r.room_id,
    r.room_name,
    COUNT(p.id)::BIGINT AS player_count,
    r.created_at
  FROM game_rooms r
  LEFT JOIN game_players p ON r.room_id = p.room_id
  WHERE r.game_type = p_game_type
    AND r.created_at > NOW() - INTERVAL '1 hour'
  GROUP BY r.id, r.room_id, r.room_name, r.created_at
  HAVING COUNT(p.id) < 2
  ORDER BY r.created_at DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
