-- Таблица для сохранения состояния игр (Yjs state)
CREATE TABLE IF NOT EXISTS game_state (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id TEXT NOT NULL UNIQUE,
  state_data TEXT, -- Base64 закодированное состояние Yjs
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Индекс для быстрого поиска по room_id
CREATE INDEX IF NOT EXISTS idx_game_state_room_id ON game_state(room_id);

-- Права
GRANT ALL ON game_state TO anon, authenticated;
GRANT ALL ON SEQUENCE game_state_id_seq TO anon, authenticated;
